# Generated by Django 3.2.5 on 2022-06-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_author_lastlogout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='lastLogout',
            new_name='lastLogin',
        ),
    ]
