# Generated by Django 3.2.5 on 2022-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_lastlogout_author_lastlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='discription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
