# Generated by Django 3.2.5 on 2022-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220606_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
