# Generated by Django 3.2.5 on 2022-06-08 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user_img/'),
        ),
        migrations.CreateModel(
            name='ImgInArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='article_img/')),
                ('articleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.article')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.author')),
            ],
        ),
    ]
