# Generated by Django 3.2.5 on 2022-06-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20220608_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='condition',
        ),
    ]
