# Generated by Django 3.2.5 on 2022-06-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_article_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='imginarticle',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
