# Generated by Django 3.2.5 on 2022-06-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_imginarticle_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='discription',
        ),
    ]
