# Generated by Django 4.0.4 on 2022-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commentsCount',
            field=models.IntegerField(default=0),
        ),
    ]
