# Generated by Django 4.0.4 on 2022-06-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_article_commentscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='firstCreate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
