# Generated by Django 4.0.4 on 2022-06-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_article_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='article_file/')),
                ('articleId', models.IntegerField(null=True)),
                ('userId', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ImgInArticle',
        ),
    ]
