# Generated by Django 4.0.4 on 2022-06-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='articleId',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='stars',
            name='userId',
            field=models.CharField(max_length=1000000),
        ),
    ]
