# Generated by Django 4.0.4 on 2022-06-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_alter_stars_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stars',
            table='pri_key',
        ),
    ]
