# Generated by Django 4.0.4 on 2022-06-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0004_alter_stars_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='articleId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stars',
            name='userId',
            field=models.CharField(max_length=50),
        ),
    ]
