# Generated by Django 4.0.4 on 2022-06-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0005_alter_stars_articleid_alter_stars_userid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stars',
            table=None,
        ),
    ]
