# Generated by Django 4.0.4 on 2022-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0006_alter_stars_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('followId', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('userId', 'followId')},
            },
        ),
    ]
