# Generated by Django 4.0.4 on 2022-06-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0008_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
