# Generated by Django 4.0.4 on 2022-06-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0010_history'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='history',
            unique_together=set(),
        ),
    ]
