# Generated by Django 4.0.4 on 2022-06-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_like', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comment',
            new_name='comment',
        ),
    ]
