# Generated by Django 4.0.4 on 2022-06-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_like', '0002_rename_comment_comments_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('userId', 'articleId')},
        ),
    ]
