# Generated by Django 4.0.4 on 2022-06-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_like', '0003_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articleId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
